### ISSUE TITLE
parallel computing

### ISSUE THREAD

**Issue by brianpenghe** [ulfaslak/py_pcha#6]
Thanks for this nice program.
It seems that it's only using 4 of my cores.
Is there anyway to increase the number of parallel threads?

Thanks!

**Comment by ulfaslak** [comment]
Since the software does not explicitly use any parallel processing, this is almost certainly a feature of your numpy installation. I recommend looking into something [like this](https://roman-kh.github.io/numpy-multicore/), to see if you have an installation of numpy that makes the best use of your computer.

**Comment by brianpenghe** [comment]
> Since the software does not explicitly use any parallel processing, this is almost certainly a feature of your numpy installation. I recommend looking into something [like this](https://roman-kh.github.io/numpy-multicore/), to see if you have an installation of numpy that makes the best use of your computer.

Thanks for your suggestion. It turned out that my numpy uses all my cores when running the test.py. I guess it may be something else.
